name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk
      - name: Build, Package, Verify, Deploy
        run: mvn -B clean package license:check-file-header deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
